Workaround to fix NCCL crashing when running multinode DDP on Tesla 4.
NCCL backend doesn't seem to close the channels gracefully leading to
a crash of nccl at the end of the training even if the training was
successfully completed. Moving to the latest nccl version fixes the
issue but requires several packages to have a compatible version.

The barbarian callstack from the master node looks like this :

cisco-t4x1-bm0:5856:5922 [0] NCCL INFO comm 0x5f203c46e200 rank 0 nranks 2 cudaDev 0 busId 65000 - Abort COMPLETE
[E ProcessGroupNCCL.cpp:577] [Rank 0] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:583] [Rank 0] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:1414] [PG 0 Rank 0] Process group watchdog thread terminated with exception: NCCL error: remote process exited or there was a network error, NCCL version 2.20.5
ncclRemoteError: A call failed possibly due to a network error or a remote process exiting prematurely.
Last error:
socketProgress: Connection closed by remote peer cisco-t4x1-bm1.ucsx.local<55696>
Exception raised from checkForNCCLErrorsInternal at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1723 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x78cd5fb7a897 in /.pyenv/versions/3.11.9/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::checkForNCCLErrorsInternal(std::shared_ptr<c10d::NCCLComm>&) + 0x220 (0x78cc75e685f0 in /.pyenv/versions/3.11.9/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::WorkNCCL::checkAndSetException() + 0x7c (0x78cc75e6883c in /.pyenv/versions/3.11.9/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::watchdogHandler() + 0x180 (0x78cc75e6da60 in /.pyenv/versions/3.11.9/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x78cc75e6edcc in /.pyenv/versions/3.11.9/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0xdc253 (0x78ccc286c253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #6: <unknown function> + 0x94ac3 (0x78cd6c02bac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #7: <unknown function> + 0x126850 (0x78cd6c0bd850 in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG 0 Rank 0] Process group watchdog thread terminated with exception: NCCL error: remote process exited or there was a network error, NCCL version 2.20.5
ncclRemoteError: A call failed possibly due to a network error or a remote process exiting prematurely.
Last error:
socketProgress: Connection closed by remote peer cisco-t4x1-bm1.ucsx.local<55696>
Exception raised from checkForNCCLErrorsInternal at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1723 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x78cd5fb7a897 in /.pyenv/versions/3.11.9/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::checkForNCCLErrorsInternal(std::shared_ptr<c10d::NCCLComm>&) + 0x220 (0x78cc75e685f0 in /.pyenv/versions/3.11.9/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::WorkNCCL::checkAndSetException() + 0x7c (0x78cc75e6883c in /.pyenv/versions/3.11.9/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::watchdogHandler() + 0x180 (0x78cc75e6da60 in /.pyenv/versions/3.11.9/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x78cc75e6edcc in /.pyenv/versions/3.11.9/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0xdc253 (0x78ccc286c253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #6: <unknown function> + 0x94ac3 (0x78cd6c02bac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #7: <unknown function> + 0x126850 (0x78cd6c0bd850 in /lib/x86_64-linux-gnu/libc.so.6)

Exception raised from ncclCommWatchdog at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1418 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x78cd5fb7a897 in /.pyenv/versions/3.11.9/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xe32119 (0x78cc75af2119 in /.pyenv/versions/3.11.9/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xdc253 (0x78ccc286c253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #3: <unknown function> + 0x94ac3 (0x78cd6c02bac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #4: <unknown function> + 0x126850 (0x78cd6c0bd850 in /lib/x86_64-linux-gnu/libc.so.6)

E1006 07:14:13.609000 130462216223616 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: -6) local_rank: 0 (pid: 5856) of binary: /.pyenv/versions/3.11.9/bin/python3.11
Traceback (most recent call last):
  File "/.pyenv/versions/3.11.9/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/.pyenv/versions/3.11.9/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/.pyenv/versions/3.11.9/lib/python3.11/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/.pyenv/versions/3.11.9/lib/python3.11/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/.pyenv/versions/3.11.9/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.pyenv/versions/3.11.9/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
=====================================================
train.py FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-06_07:14:13
  host      : cisco-t4x1-bm0
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 5856)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 5856
=====================================================

Signed-off-by: Aymen Zayet <aymen.zayet@flex.ai>